rossum_api/models/annotation.py
- this raised exception when parsing elis response for methods like `list_all_annotations`
- can this fix be released please? I need the fixed version in releases so I can include its hashed version in requirements for our project
=> fix: change Annotation.confirmed_at type to str instead of datetime

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_client_sync.py, tests/test_api_client.py
I've used this method when porting E2E Test Runner to `rossum-api` to implement the annotation process since I wasn't sure how common this use case is. I think it's useful to have this method even if we add support for updating annotations to the client.
=> Add request_json method to ElisAPIClient

.pre-commit-config.yaml, conditional-commitizen.sh
Make it passing when there is no commit.
=> chore: do not run commitizen when there is no commit

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/test_api_client.py
Simple method for obtaining current token. 
- Client is authenticated first if no token exist. 
- Possibility to force refreshing.
Useful for situations, where you need to just obtain token from username/password and pass it elsewhere (without calling any rossum api endpoint).
We (exe) use this in a fastAPI path function dependency, that obtains rossum token from username/password obtained from hook secrets.
e.g. function:
```
async def _get_rossum_token_from_credentials(user: str, password: str, base_url: str) -> str:
"""Get token from Rossum API."""
client = ElisAPIClient(
username=user, password=password, base_url=f"{base_url}/api/v1"
)
return await client.get_token()
```
=> feat: add get_token method to Api client

rossum_api/models/document.py
This created hard-to-debug problem because some of the documents being fetched had `creator==None`.
I think we should maybe consider less strict validation for our internal data models unless we are super confident all are always up to date and correct. Because this can cause quite annoying problems in client code.
=> fix(models:document): define `creator` attribute as optional

rossum_api/models/hook.py
When retrieving valid hook object, I got validation errors, because Elis send `None` in these attributes. The validation needs to be more benevolent for this models 
(this already happened also for other models, we should probably check the annotations in near future, because these are blocking issues).
=> fix(models:hook): define attributes `guide`, `read_more_url` and `extension_image_url` as optional

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_client_sync.py, tests/test_api_client.py
Added method to enable requesting raw binary data from endpoints such as `pages/<id>/preview`.
=> feat(rossum_sdk/api_client): add `request` method to ElisApiClient

rossum_api/api_client.py, tests/test_api_client.py
There is no way how to limit the number of pages or elements that will be fetched when listing e.g. `annotations`. 
Its important especially because of [EXE-1026](https://rossumai.atlassian.net/browse/EXE-1026) .
=> feat(api_client): allow to set max pages limit in filters

rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_client_sync.py
Some endpoints that returns paginated responses are not supported by the client. To not be forced to periodically update the client and be more future proof, I added generic method for paginated responses.
I need it in my case for "hook_templates". Currently I have to do very ugly hack like this:
```
hook_templates = list(
elis_client._iter_over_async(
elis_client.elis_api_client._http_client.fetch_all(f"hook_templates")
)
)
```
With this MR, I will be able to just do:
```
hook_templates = list(elis_client.request_paginated("hook_templates"))
```
=> feat(elis_api_client): add generic method for requests to paginated resources

rossum_api/models/queue.py
The [docs](https://elis.rossum.ai/api/docs/#metadata) say that `metadata` can be a custom JSON object, but the `Queue` model (this one only) restricts it to `dict[str, str]`. This causes confusing uncaught exceptions when fetching queues with more complex metadata objects like:
```python
WrongTypeError(field_path=field.name, field_type=field_type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "metadata" - should be "Dict" instead of value "{'queueTemplate': 'taxinvoiceeu', 'distributive_fields': {'line_items': {'item_desc': {'schema_ids': ['article'], 'preferred_direction': 'downwards'}, 'item_number_plate': {'schema_ids': ['number_plate'], 'preferred_direction': 'downwards'}}}}" of type "dict"
```
The [docs](https://elis.rossum.ai/api/docs/#queue) say:
``` …
```
=> fix(models): make queue model compliant with API docs

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_annotations.py
Adding new method for the new `search` endpoint: https://elis.rossum.ai/api/docs/internal/#search-for-annotations
Needed to add new argument to the `fetch_all` method of ApiClient to allow for passing json payload to the request.
=> Add search_for_annotations method

README.md, rossum_api/__init__.py, rossum_api/elis_api_client_sync.py, test.py, tests/conftest.py, tests/e2e.py, tests/elis_api_client/test_client_sync.py
Importing stuff from internal subpackages like
```python
from rossum_api.elis_api_client import ElisAPIClient
from rossum_api.api_client import APIClientError
```
always feels bad. :( 
The standard is to "export" public interface in the root package like
```python
from httpx import AsyncClient, HTTPStatusError
```
=> feat: export public interface in root package

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_annotations.py, tests/elis_api_client/test_client_sync.py, tests/elis_api_client/test_connectors.py, tests/elis_api_client/test_hooks.py, tests/elis_api_client/test_inboxes.py, tests/elis_api_client/test_organizations.py, tests/elis_api_client/test_queues.py, tests/elis_api_client/test_schemas.py, tests/elis_api_client/test_user_roles.py, tests/elis_api_client/test_users.py, tests/elis_api_client/test_workspaces.py, tests/test_api_client.py
This is not only cleaner but will be useful when implementing custom de-serializers.
=> refactor: Use an enum instead of strings to identify API resources

.pre-commit-config.yaml, rossum_api/models/automation_blocker.py, tests/elis_api_client/test_annotations.py
According to the docs https://elis.rossum.ai/api/docs/#automation-blocker, `samples` should be a list, not a dictionary.
=> fix(models:automation_blocker): fix type of `samples`

Makefile, rossum_api/api_client.py, tests/test_api_client.py
Currently, the api client tries to re-authenticate using credentials (username + password) in case the token is invalid (401 response is received on any request). However, attempting this when there were no credentials configured when creating the client doesn't make sense. It results in a misleading 400 error saying `{"password": ["This field may not be blank."]}`.
This change fixes it by transparently returning the 401 when the token is invalid and the credentials are missing. This way, the code using the client can deal with the invalid token issue on its own (e.g. display a user friendly message).
=> fix(api-client): do not reauth if no credentials are available

pyproject.toml, setup.py
Use solely pyproject.toml with a correctly specified package version and drop no more needed setup.py.
Fixes #58.
=> packaging: Use solely pyproject.toml

rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py
Iterator is a better type for the method return value, since it correctly type checks the use of `next()`. Iterable interface doesn't.
=> fix: use Iterator instead of Iterable types

rossum_api/api_client.py, tests/test_api_client.py
This fixes the sdk prepending `http://` urls with `base_url`.
=> fix: handle http:// urls for local development

rossum_api/domain_logic/resources.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, rossum_api/models/__init__.py, rossum_api/models/engine.py, tests/elis_api_client/test_engines.py
Implement support for retrieving `EngineFields` (in both sync and async versions). See the [documentation](https://elis.rossum.ai/api/docs/internal/#list-all-engine-fields) for details.
=> elis_api_client: Add support for retrieving EngineFields (sync + async)

rossum_api/api_client.py, rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/test_api_client.py
Per EXE-2704.
1. Both export methods were not allowing filters, fixed that.
2. Some clients use more information from the exception and were wrapping APIClientError, which was unfortunate. Let me know if I should reformat it somehow, there is definitely wiggle room on this change.
=> feat: Improve export helpers method, enrich exception inf

rossum_api/elis_api_client.py, rossum_api/elis_api_client_sync.py, tests/elis_api_client/test_engines.py
The new name better conveys the essence that we're retrieving only a **list of queues** associated with the **given engine**.
=> refactor: Rename retrieve_engine_queue_stats to retrieve_engine_queues

rossum_api/clients/internal_async_client.py, rossum_api/clients/internal_sync_client.py, tests/internal_clients/test_internal_async_client.py, tests/internal_clients/test_internal_sync_client.py
Based on the official documentation, the API supports "Bearer" together with "token". To standardize and allow easy extension of the SDK, it is proposed to run "Beared" instead of "token" as a part of the Header.
=> fix: switch from token header to Bearer auth and update tests

rossum_api/clients/external_async_client.py, rossum_api/clients/external_sync_client.py
Add a missing `authenticate` method to **Rossum API client** (both **sync** and **async** versions) so that it can be called directly when testing whether credentials are properly set up.
=> feat: Add authenticate method to Rossum API client 
